/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface BuildCompositedImageOptions {
  backgroundColor: Array<number>
  resizeMode?: object
  offsetMode?: object
}
export function sum(a: number, b: number): number
export function buildCompositedImage(productBuffer: Buffer, overlayBuffer: Buffer, options: BuildCompositedImageOptions): void
